### ISSUE TITLE
Document how to use it without nodejs

### ISSUE THREAD

**Issue by vaijira** [dancespiele/yew_styles#86]
I don't know if i'm doing correctly but i'm not using nodejs and i'm simply adding <link href="/node_modules/yew-styles/main.css" rel="stylesheet" /> in the html page.

**Comment by dancespiele** [comment]
@vaijira If you don't use with [parceljs](https://github.com/dancespiele/yew-parcel-template) for now you need to download manually the [css file](https://www.npmjs.com/package/yew-styles) and include the path in your html file.
In the future I will add a build for it

**Comment by tv42** [comment]
Seeing "npm install" in a project that described itself as "without JavaScript dependencies" was weird.

**Comment by dancespiele** [comment]
It is for building and running the project, the same you can run it with [Truck](https://github.com/thedodd/trunk) which I think it is everything based in rust then you don't need to use any javascript, but css need to download manually in that case. The project itself doesn't have any Javascript dependency

**Comment by dancespiele** [comment]
@vaijira @tv42 I created this [template](https://github.com/dancespiele/yew_styles_trunk_template) to use Yew Styles in apps without javascript involve, with this I close this issue
